### ISSUE TITLE
Client cannot connect to PHP 7 servers of ports ≥32768

### ISSUE THREAD

**Issue by PEMapModder** [PocketMine/RakLib#16]
Reference: PocketMine/PocketMine-MP#3912

**Comment by jazzwhistle** [comment]
Are you sure this is a RakLib problem? It is now fixed in recent IM builds, but I don't see any changes to their RakLib that would explain why their version works, and official doesn't - this is their last RakLib commit from 13 days ago

https://github.com/ImagicalMine/ImagicalMine/commit/0b69d1d04bc32bd08168a3a2a9e6911e59f00fc0

**Comment by PEMapModder** [comment]
@jazzwhistle then please link to the commit that actually fixed it.

**Comment by jazzwhistle** [comment]
@PEMapModder if you are correct that this is a RakLib issue, then that is probably the commit that fixed it..

**Comment by jazzwhistle** [comment]
I've fixed this issue in the official, Genisys and CS builds by simply replacing the raklib folder with that of IM

**Comment by PEMapModder** [comment]
So that means it is RakLib issue!

**Comment by jazzwhistle** [comment]
You were indeed right, thanks! If I have time I'll diff the folders and see what I come up with

**Comment by ZizzyZizzy** [comment]
Thanks. It works fine now on Genisys builds, which do include the patched code.
